include $(THEOS)/makefiles/common.mk

ARCHS = arm64 arm64e

TOOL_NAME = postinst

postinst_FILES = main.m
postinst_CFLAGS = -fobjc-arc
postinst_INSTALL_PATH = /DEBIAN

include $(THEOS_MAKE_PATH)/tool.mk
